// THIS FILE IS AUTOMATICALLY GENERATED
// DON'T CHANGE IT IN ORDER TO MAKE IT PROPERLY WORK!
export default defineNuxtPlugin(() => ({
  provide: {
    routeNames: {
      voting: 'voting',
      index: 'index',
      gallery: 'gallery',
      breeds: 'breeds'
    }
  }
}))
